### ISSUE TITLE
Huygen Physics Simulation 

### ISSUE THREAD

**Issue by coder0xff** [Wintergatan/Tightinator#56]
I've done some physics modeling of the Huygens chain drive with flywheel and governor, but it didn't account for the effects of varying power input. While it's a closed form equation and produces an RPM plot instantaneously, it's not detailed enough to reflect real world observations when tight timing is essential. An explicitly integrated approximation may prove to be more useful.

A physics simulation works well with an arbitrary choice of an input work function, including one modeling a "Martin." Moreover, the load function can be arbitrary, for instance simulating the actuation of marble gates. Experimenting with different flywheel weights, gear ratios, cranks, load profiles, etc can be done virtually before physical construction.

The question remains, however, of utility. Putting together a bespoke physics simulation is a substantial effort. I'd like to gauge the need for such a tool before committing to it.

**Comment by TLMcNulty** [comment]
I think the general concept of a physics simulation could be very helpful to the project as a whole, but I don't know if it's helpful in this instance or with this tool. 

We built this in direct contact with Martin, and the primary goal was to produce something that would replace the tedium of the peak detection process. I don't know of any of his processes that a sim would help with, beyond testing the actual forces throughout any one incantation of a drivetrain or transmission. The project and design ideas can change on a whim from week to week, so there's no guarantee that a Huygen drive system will be used in the coming weeks, or any sort of final version of the machine.

**Comment by TLMcNulty** [comment]
Closing stale issue
